---
# tasks file for ansible_compliance_var1

- name:  checking for template
  template:
    src: "{{ role_path }}/files/file_to_check.j2"
    dest: /tmp/file_to_check.txt
    mode: '0777'
  register: creating_file
  tags:
    - create_file

- name: echoing file
  debug:
    var: creating_file
  tags:
    - create_file

- name:  checking for template
  template:
    src: "{{ role_path }}/files/file_to_check.j2"
    dest: /tmp/file_to_check.txt
    mode: '0777'
  check_mode: yes
  diff: yes
  register:
    checking_file
  tags:
    - check_file

- name: Echoing file
  debug:
    var: checking_file
  tags:
    - check_file

- name: Echoing when only changed
  debug:
    var: checking_file
  when: checking_file.changed == True
  tags:
    - check_file

- name: Deleting the file with report
  file:
    path: /nginx/file_compare.html
    state: absent
  delegate_to: node10.da-demo.test
  tags:
    - check_file
    - create_file

- name: creating the file with difference report
  blockinfile:
    path: "/nginx/file_{{ansible_hostname}}_before.html "
    block: | 
      "<html><body>
      <code>HOSTNAME:BEFORE  :  {{ ansible_hostname }}{{ checking_file.diff[0].before}} <br></code>
       </body></html>
    state: present
    create: yes
    marker: "# COMPARSION CASE"
  when: checking_file.changed == True
  delegate_to: node10.da-demo.test
  tags:
    - check_file

- name: creating the file with difference report_2
  blockinfile:
    path: "/nginx/file_{{ansible_hostname}}_after.html "
    block: | 
      "<html><body>
      <code>HOSTNAME:AFTER  :  {{ ansible_hostname }}{{ checking_file.diff[0].after}} <br></code>
       </body></html>
    state: present
    create: yes
    marker: "# COMPARSION CASE"
  when: checking_file.changed == True
  delegate_to: node10.da-demo.test
  tags:
    - check_file
