---
# tasks file for ansible_compliance_var1

- name:  checking for template
  template:
    src: "{{ role_path }}/files/file_to_check.j2"
    dest: /tmp/file_to_check.txt
    mode: '0777'
  register: creating_file
  tags:
    - create_file

- name: echoing file
  debug:
    var: creating_file
  tags:
    - create_file

- name:  checking for template
  template:
    src: "{{ role_path }}/files/file_to_check.j2"
    dest: /tmp/file_to_check.txt
    mode: '0777'
  check_mode: yes
  diff: yes
  register:
    checking_file
  tags:
    - check_file

- name: Echoing file
  debug:
    var: checking_file
  tags:
    - check_file

- name: Echoing when only changed
  debug:
    var: checking_file
  when: checking_file.changed == True
  tags:
    - check_file

- name: Deleting BEFORE report
  file:
    path: "/nginx/file_{{ansible_hostname}}_before.txt"
    state: absent
  delegate_to: node10.da-demo.test
  tags:
    - check_file
    - create_file

- name: Deleting AFTER report
  file:
    path: "/nginx/file_{{ansible_hostname}}_after.txt"
    state: absent
  delegate_to: node10.da-demo.test
  tags:
    - check_file
    - create_file

- name: DELETING DIFF REPORT
  file:
    path: "/nginx/file_{{ansible_hostname}}_diff.txt"
    state: absent
  delegate_to: node10.da-demo.test
  tags:
    - check_file
    - create_file

- name: CREATING THE FILE FOR BEFORE REPORT
  lineinfile:
    path: "/nginx/file_{{ansible_hostname}}_before.txt"
    line: "{{ ansible_hostname }} - {{ checking_file.diff[0].before}}"
    state: present
    create: yes
  when: checking_file.changed == True
  delegate_to: node10.da-demo.test
  tags:
    - check_file

- name: CREATING THE FILE FOR AFTER REPORT
  lineinfile:
    path: "/nginx/file_{{ansible_hostname}}_after.txt"
    line: "{{ ansible_hostname }} - {{ checking_file.diff[0].after}}"
    state: present
    create: yes
  when: checking_file.changed == True
  delegate_to: node10.da-demo.test
  tags:
    - check_file

- name: CREATING THE FILE FOR DIFF REPORT
  shell: "diff /nginx/file_{{ansible_hostname}}_before.txt /nginx/file_{{ansible_hostname}}_after.txt > /nginx/file_{{ansible_hostname}}_diff.txt -y"
  when: checking_file.changed == True
  delegate_to: node10.da-demo.test
  tags:
    - check_file
  ignore_errors: true
